/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv.GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qltv.DAL.DocGiaModify;
import qltv.DTO.DocGia;

/**
 *
 * @author Lenovo L340
 */
public class DocGiaMannagement extends javax.swing.JPanel {

    DefaultTableModel tableModel;
    
    /**
     * Creates new form TheMuonMannagement
     */
    public DocGiaMannagement() {
        initComponents();
        
        tableModel = (DefaultTableModel) tbtheTV.getModel();
        showTheTV();
    }

    private void showTheTV(){
        List<DocGia> TheMuonList = DocGiaModify.finAll();
        
        tableModel.setRowCount(0);
        TheMuonList.forEach((themuon) -> {
            tableModel.addRow(new Object[]{themuon.getMathe(),
                themuon.getNgayBD(),themuon.getNgayKT(),themuon.getGhichu(),themuon.getTendocgia(),themuon.getLop(),
                themuon.getKhoa(),themuon.getNgaySinh()});
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtheTV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnthem1 = new javax.swing.JButton();
        txtmathe = new javax.swing.JTextField();
        txtngaykt = new javax.swing.JTextField();
        txtgc = new javax.swing.JTextField();
        txttendg = new javax.swing.JTextField();
        txtkhoa = new javax.swing.JTextField();
        txtlop = new javax.swing.JTextField();
        txtngaybd = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();

        jLabel2.setText("Ghi chú");

        jLabel3.setText("Ngày hết hạn");

        jLabel4.setText("Tên đọc giả");

        jLabel7.setText("Ngày sinh");

        jLabel5.setText("Khoa");

        jLabel8.setText("Mã Thẻ");

        jLabel6.setText("Lớp");

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/Actions-document-edit-icon-16.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ngày bắt đầu");

        tbtheTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Thẻ", "Ngày bắt đầu", "Ghi chú", "Tên đọc giả", "Ngày kết thúc", "Lớp", "Khoa", "Ngày sinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtheTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtheTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtheTV);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("Quản Lý Thẻ Thư Viện");

        jToolBar1.setRollover(true);

        btnthem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/new-icon-16.png"))); // NOI18N
        btnthem1.setText("Thêm");
        btnthem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem1ActionPerformed(evt);
            }
        });

        txtmathe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatheFocusLost(evt);
            }
        });

        txttendg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttendgFocusLost(evt);
            }
        });

        txtkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaActionPerformed(evt);
            }
        });

        txtngaybd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtngaybdFocusLost(evt);
            }
        });
        txtngaybd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaybdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttendg)
                            .addComponent(txtlop)
                            .addComponent(txtkhoa)
                            .addComponent(txtngaysinh)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtgc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmathe)
                            .addComponent(txtngaybd)
                            .addComponent(txtngaykt))))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmathe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngaybd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnthem1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttendg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        List<DocGia> list = new ArrayList<>();
        try {
            list = DocGiaModify.timkiem(txtmathe.getText());
                    if(list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mã thẻ không tồn tại!");
                        txtmathe.setText("");
                    }else{
                        DocGiaModify.delete(txtmathe.getText());
                        JOptionPane.showMessageDialog(this, "Bạn đã xóa thông tin thẻ thành công.");
                        showTheTV();      
                        resetData();
                    }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        List<DocGia> list = new ArrayList<>();
        try {
            String maThe = txtmathe.getText();
            String ngayBD = txtngaybd.getText();
            String ngayKT = txtngaykt.getText();
            String ghichu = txtgc.getText();
            String tendocgia = txttendg.getText();
            String lop = txtlop.getText();
            String khoa = txtkhoa.getText();
            String ngaysinh = txtngaysinh.getText();
            DocGia tm = new DocGia(maThe, tendocgia, ngayBD, ngayKT, ghichu, lop, khoa, ngaysinh);
            list = DocGiaModify.timkiem(maThe);
                    if(list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Không được phép sửa mã thẻ!");
                        txtmathe.setText("");
                    }else{
                        DocGiaModify.update(tm);
                        JOptionPane.showMessageDialog(this, "Bạn đã sửa thông tin thẻ thành công.");
                        showTheTV();      
                        resetData();
                    }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnsuaActionPerformed

    private void tbtheTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtheTVMouseClicked
        // TODO add your handling code here:
        //if (evt.getClickCount()==2){
            int index=tbtheTV.getSelectedRow();
            txtmathe.setText((String)(tableModel.getValueAt(index, 0)));
            txtngaybd.setText((String)tableModel.getValueAt(index, 1));
            txtngaykt.setText((String)tableModel.getValueAt(index, 4));
            txtgc.setText((String)tableModel.getValueAt(index, 2));
            txttendg.setText((String)tableModel.getValueAt(index, 3));
            txtlop.setText((String)tableModel.getValueAt(index, 5));
            txtkhoa.setText((String)tableModel.getValueAt(index, 6));
            txtngaysinh.setText((String)tableModel.getValueAt(index, 7));

            // }
    }//GEN-LAST:event_tbtheTVMouseClicked

     public void resetData(){
        txtmathe.setText("");
        txtngaybd.setText("");
        txtngaykt.setText("");
        txtgc.setText("");
        txttendg.setText("");
        txtlop.setText("");
        txtkhoa.setText("");
        txtngaysinh.setText("");
        
    }
    
    private void btnthem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem1ActionPerformed
        // TODO add your handling code here:
        List<DocGia> list = new ArrayList<>();
        try {
            String maThe = txtmathe.getText();
            String ngayBD = txtngaybd.getText();
            String ngayKT = txtngaykt.getText();
            String ghichu = txtgc.getText();
            String tendocgia = txttendg.getText();
            String lop = txtlop.getText();
            String khoa = txtkhoa.getText();
            String ngaysinh = txtngaysinh.getText();
            DocGia tm = new DocGia(maThe, tendocgia, ngayBD, ngayKT, ghichu, lop, khoa, ngaysinh);
            list = DocGiaModify.timkiem(maThe);
                    if(!list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mã thẻ đã tồn tại, vui lòng nhập lại mã thẻ");
                        txtmathe.requestFocus();
                        txtmathe.setText("");
                    }else{
                            DocGiaModify.insert(tm);
                            JOptionPane.showMessageDialog(this, "Bạn đã thêm thẻ mới thành công.");
                            showTheTV();      
                            resetData();
                    }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnthem1ActionPerformed

    private void txtngaybdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaybdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaybdActionPerformed

    private void txtkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaActionPerformed

    private void txtmatheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatheFocusLost
        // TODO add your handling code here:
         if (this.isVisible()){
            String ma = txtmathe.getText();
            String reg = "^\\w{2}\\d{3}$";
            if(ma.length() > 0){
                if(!ma.matches(reg)){
                    JOptionPane.showMessageDialog(this, "Sai định dạng, nhập lại mã thẻ, ví dụ : MT000 !");
                    txtmathe.requestFocus();
                    resetData();
                }else {
                        
                }
            }else{
                JOptionPane.showMessageDialog(this, "Mã thẻ mượn không được để trống!");
                 txtmathe.requestFocus();
                }
       }
    }//GEN-LAST:event_txtmatheFocusLost

    private void txtngaybdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtngaybdFocusLost
        
    }//GEN-LAST:event_txtngaybdFocusLost

    private void txttendgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttendgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttendgFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbtheTV;
    private javax.swing.JTextField txtgc;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextField txtlop;
    private javax.swing.JTextField txtmathe;
    private javax.swing.JTextField txtngaybd;
    private javax.swing.JTextField txtngaykt;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txttendg;
    // End of variables declaration//GEN-END:variables
}
