/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv.GUI;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qltv.DAL.PhieuMuonModify;
import qltv.DTO.PhieuMuonTra;
import qltv.DTO.MuonTL;
/**
 *
 * @author Lenovo L340
 */
public class PhieuMuonTraMannagement extends javax.swing.JPanel {

    DefaultTableModel tableModel;
    /**
     * Creates new form PhieuMuonTraMannagement
     */
    public PhieuMuonTraMannagement() {
        initComponents();
        tableModel = (DefaultTableModel) tblmuontratl.getModel();
        showPhieuMuon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnthem1 = new javax.swing.JButton();
        txtmamuontra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmatl = new javax.swing.JTextField();
        txtngaymuon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmuontratl = new javax.swing.JTable();
        txtmathe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtghichu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        btnthem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/new-icon-16.png"))); // NOI18N
        btnthem1.setText("Mượn Tài Liệu");
        btnthem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem1ActionPerformed(evt);
            }
        });

        txtmamuontra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmamuontraFocusLost(evt);
            }
        });

        jLabel8.setText("Mã mượn trả");

        jLabel1.setText("Mã thẻ");

        tblmuontratl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Mã thẻ", "Mã tài liệu", "Ngày mượn", "Ngày trả", "Đã trả", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmuontratl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmuontratlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmuontratl);

        txtmathe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatheFocusLost(evt);
            }
        });
        txtmathe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatheActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày mượn");

        jLabel3.setText("Mã tài liệu");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("Mượn tài liệu");

        jLabel7.setText("Ghi chú");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtghichu))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtngaymuon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmamuontra)
                                    .addComponent(txtmathe)
                                    .addComponent(txtmatl))))
                        .addGap(51, 51, 51)
                        .addComponent(btnthem1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmamuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmathe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthem1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void showPhieuMuon(){
        List<PhieuMuonTra> TheMuonList = PhieuMuonModify.finAll();
        
        tableModel.setRowCount(0);
        TheMuonList.forEach((themuon) -> {
            tableModel.addRow(new Object[]{themuon.getMaMuonTra(),
                themuon.getMaThe(),themuon.getMaTL(),themuon.getNgayMuon(),themuon.getNgayTra(),themuon.getDaTra(),themuon.getGhiChu()});
        });
    }
     
      public void resetData(){
        txtmamuontra.setText("");
        txtmathe.setText("");
        txtmatl.setText("");
        txtngaymuon.setText("");
        txtghichu.setText("");
        
    }
     
    private void btnthem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem1ActionPerformed
        // TODO add your handling code here:
        List<PhieuMuonTra> list = new ArrayList<>();
        try {
            String maMuonTra = txtmamuontra.getText();
            String maThe = txtmathe.getText();
            String maTL = txtmatl.getText();
            String ngayMuon = txtngaymuon.getText();
            String ghiChu = txtghichu.getText();
            MuonTL tm = new MuonTL(maMuonTra, maThe, maTL, ngayMuon, ghiChu);
            list = PhieuMuonModify.timkiem(maMuonTra);
            if(!list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Mã thẻ đã tồn tại, vui lòng nhập lại mã thẻ");
                txtmamuontra.requestFocus();
                txtmamuontra.setText("");
            }else{
                PhieuMuonModify.MuonTL(tm);
                JOptionPane.showMessageDialog(this, "Bạn đã mượn sách thành công.");
                showPhieuMuon();
                resetData();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnthem1ActionPerformed

    private void txtmamuontraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmamuontraFocusLost
        // TODO add your handling code here:
        if (this.isVisible()){
            String ma = txtmamuontra.getText();
            String reg = "^\\w{2}\\d{3}$";
            if(ma.length() > 0){
                if(!ma.matches(reg)){
                    JOptionPane.showMessageDialog(this, "Sai định dạng, nhập lại mã thẻ, ví dụ : MM000 !");
                    txtmamuontra.requestFocus();
                    resetData();
                }else {

                }
            }else{
                JOptionPane.showMessageDialog(this, "Mã thẻ mượn không được để trống!");
                txtmamuontra.requestFocus();
            }
        }
    }//GEN-LAST:event_txtmamuontraFocusLost

    private void tblmuontratlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmuontratlMouseClicked

            int index=tblmuontratl.getSelectedRow();
            txtmamuontra.setText((String)(tableModel.getValueAt(index, 0)));
            txtmathe.setText((String)tableModel.getValueAt(index, 1));
            txtmatl.setText((String)tableModel.getValueAt(index, 2));
            txtngaymuon.setText((String)tableModel.getValueAt(index, 3));
            txtghichu.setText((String)tableModel.getValueAt(index, 6));

    }//GEN-LAST:event_tblmuontratlMouseClicked

    private void txtmatheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatheFocusLost

    }//GEN-LAST:event_txtmatheFocusLost

    private void txtmatheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblmuontratl;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtmamuontra;
    private javax.swing.JTextField txtmathe;
    private javax.swing.JTextField txtmatl;
    private javax.swing.JTextField txtngaymuon;
    // End of variables declaration//GEN-END:variables
}
