/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv.GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qltv.DAL.TaiLieuModifiy;
import qltv.DTO.TaiLieu;
/**
 *
 * @author Lenovo L340
 */
public class TaiLieuManagment extends javax.swing.JPanel {

    DefaultTableModel tableModel;
    /**
     * Creates new form TaiLieuManagment
     */
    public TaiLieuManagment() {
        initComponents();
        
        tableModel = (DefaultTableModel) tblTaiLieu.getModel();
        showTaiLieu();
    }

    
    private void showTaiLieu(){
        List<TaiLieu> TaiLieuList = TaiLieuModifiy.finAll();
        
        tableModel.setRowCount(0);
        TaiLieuList.forEach((tailieu) -> {
            tableModel.addRow(new Object[]{tailieu.getMaTL(),
                tailieu.getTenTL(),tailieu.getTacgia(),tailieu.getTheloai(),tailieu.getNXB(),tailieu.getNamXB(),
                tailieu.getSoluong()});
        });
    }
    
    public void resetData(){
        txtmatl.setText("");
        txttentl.setText("");
        txttacgia.setText("");
        txttheloai.setText("");
        txtnhaXB.setText("");
        txtnamxb.setText("");
        txtsl.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnamxb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiLieu = new javax.swing.JTable();
        txttentl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnthem = new javax.swing.JButton();
        txtmatl = new javax.swing.JTextField();
        txtnhaXB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        txtsl = new javax.swing.JTextField();
        txttacgia = new javax.swing.JTextField();
        txttheloai = new javax.swing.JTextField();

        jLabel1.setText("Tên Tài Liệu");

        tblTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tài Liệu", "Tên Tài Liệu", "Tác giả", "Thể Loại", "Nhà Xuất Bản", "Năm Xuất Bản", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTaiLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaiLieu);

        txttentl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttentlFocusLost(evt);
            }
        });
        txttentl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentlActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/Actions-document-edit-icon-16.png"))); // NOI18N
        jLabel9.setText("Quản Lý Tài Liệu");

        jToolBar1.setRollover(true);

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/new-icon-16.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        txtmatl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatlFocusLost(evt);
            }
        });

        jLabel2.setText("Thể Loại");

        jLabel3.setText("Tác Giả");

        jLabel4.setText("Nhà Xuất Bản");

        jLabel5.setText("Số Lượng");

        jLabel8.setText("Mã Tài Liệu");

        jLabel6.setText("Năm Xuất Bản");

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltv/icon_java/Actions-document-edit-icon-16.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        txtsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtslActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamxb)
                            .addComponent(txtsl)
                            .addComponent(txtnhaXB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmatl)
                                    .addComponent(txttentl)
                                    .addComponent(txttacgia)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttheloai)))))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttentl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnhaXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTaiLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiLieuMouseClicked
        // TODO add your handling code here:
        //if (evt.getClickCount()==2){
            int index=tblTaiLieu.getSelectedRow();
            txtmatl.setText((String)(tableModel.getValueAt(index, 0)));
            txttentl.setText((String)(tableModel.getValueAt(index, 1)));
            txttacgia.setText((String)(tableModel.getValueAt(index, 2)));
            txttheloai.setText((String)(tableModel.getValueAt(index, 3)));
            txtnhaXB.setText((String)(tableModel.getValueAt(index, 4)));
            txtnamxb.setText((String)(tableModel.getValueAt(index, 5).toString()));
            txtsl.setText((String)(tableModel.getValueAt(index, 6).toString()));

            // }
    }//GEN-LAST:event_tblTaiLieuMouseClicked

    private void txttentlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentlActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        List<TaiLieu> list = new ArrayList<>();
        try {
            String maTL = txtmatl.getText();
            String tenTL = txttentl.getText();
            String tacGia = txttacgia.getText();
            String theloai = txttheloai.getText();
            String nhaXB = txtnhaXB.getText();
            int namXB = Integer.parseInt(txtnamxb.getText());
            int SL = Integer.parseInt(txtsl.getText());
            TaiLieu tl = new TaiLieu(maTL, tenTL, tacGia, theloai, nhaXB, namXB, SL);
            list = TaiLieuModifiy.timkiem(maTL);
                    if(!list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mã tài liệu đã tồn tại, vui lòng nhập lại mã tài liệu !");
                        txtmatl.requestFocus();
                        txtmatl.setText("");
                    }else{
                        TaiLieuModifiy.insert(tl);
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm tài liệu mới thành công.");
                        showTaiLieu();
                        resetData();
                    }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        List<TaiLieu> list = new ArrayList<>();    
        try {
            list = TaiLieuModifiy.timkiem(txtmatl.getText());
            if(list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mã tài liệu không không tồn tại!");
                        resetData();
                    }else{
                        TaiLieuModifiy.delete(txtmatl.getText());
                        JOptionPane.showMessageDialog(this, "Bạn đã xóa thông tin tài liệu thành công.");
                        showTaiLieu();
                        resetData();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        List<TaiLieu> list = new ArrayList<>();
        try {
            String maTL = txtmatl.getText();
            String tenTL = txttentl.getText();
            String tacGia = txttacgia.getText();
            String theloai = txttheloai.getText();
            String nhaXB = txtnhaXB.getText();
            int namXB = Integer.parseInt(txtnamxb.getText());
            int SL = Integer.parseInt(txtsl.getText());
            TaiLieu tl = new TaiLieu(maTL, tenTL, tacGia, theloai, nhaXB, namXB, SL);
            list = TaiLieuModifiy.timkiem(maTL);
            if(list.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mã tài liệu không được phép sửa!");
                        txtmatl.setText("");
                    }else{
                        TaiLieuModifiy.update(tl);
                        JOptionPane.showMessageDialog(this, "Bạn đã sửa thông tin tài liệu thành công.");
                        showTaiLieu();
                        resetData();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error" +  e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void txtslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtslActionPerformed

    private void txtmatlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatlFocusLost
        // TODO add your handling code here:
       if (this.isVisible()){
            String ma = txtmatl.getText();
            String reg = "^\\w{2}\\d{3}$";
            if(ma.length() > 0){
                if(!ma.matches(reg)){
                    JOptionPane.showMessageDialog(this, "Sai định dạng, nhập lại mã tài liệu, ví dụ : TL000 !");
                    txtmatl.requestFocus();
                    resetData();
                }else{
                }
            }else{
                JOptionPane.showMessageDialog(this, "Mã tài liệu không được để trống!");
                 txtmatl.requestFocus();
                }
       }
    }//GEN-LAST:event_txtmatlFocusLost

    private void txttentlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttentlFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentlFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblTaiLieu;
    private javax.swing.JTextField txtmatl;
    private javax.swing.JTextField txtnamxb;
    private javax.swing.JTextField txtnhaXB;
    private javax.swing.JTextField txtsl;
    private javax.swing.JTextField txttacgia;
    private javax.swing.JTextField txttentl;
    private javax.swing.JTextField txttheloai;
    // End of variables declaration//GEN-END:variables
}
